{lib}: {
  username = "christian";
  userfullname = "Christian Eickhoff";
  useremail = "christian@ewolutions.de";
  # generated by `mkpasswd -m scrypt --rounds=11`
  # https://man.archlinux.org/man/crypt.5.en
  initialHashedPassword = "$7$CU..../....KDvTIXqLTXpmCaoUy2yC9.$145eM358b7Q0sRXgEBvxctd5EAuEEdao57LmZjc05D.";
  # Public Keys that can be used to login to all my PCs, Macbooks, and servers.
  #
  # Since its authority is so large, we must strengthen its security:
  # 1. The corresponding private key must be:
  #    1. Generated locally on every trusted client via:
  #      ```bash
  #      # KDF: bcrypt with 256 rounds, takes 2s on Apple M2):
  #      # Passphrase: digits + letters + symbols, 12+ chars
  #      ssh-keygen -t ed25519 -a 256 -C "christian@xxx" -f ~/.ssh/xxx
  #      ```
  #    2. Never leave the device and never sent over the network.
  # 2. Or just use hardware security keys like Yubikey/CanoKey.
  mainSshAuthorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC9115pTLLpkhhZZh6qdlurEMHDZn7Gpv3yEfAxkNvhP christian@ewolutions.de"
  ];
  secondaryAuthorizedKeys = [
  ];
   # System-Spezifikationen (öffentlich)
  systems = import ./systems.nix;
  
  # Package-Listen pro Rolle (öffentlich)
  packages = import ./packages.nix;
  
  # Rollen-Definitionen ohne sensible Daten (öffentlich)
  roles = import ./roles.nix;
  
  # Konstanten
  defaultShell = "zsh";
  stateVersion = "25.05";
  
  # Netzwerk-Konfiguration
  networking = {
    defaultFirewallPorts = [ 22 80 443 ];
    trustedNetworks = [ "192.168.1.0/24" "10.0.0.0/8" ];
  };
  
  # Standard-Verzeichnisse
  directories = {
    secrets = ../secrets;
    home = ../home;
    hosts = ../hosts;
  };

}
