# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  # Ensure deep sleep is the default suspend mode
  boot = {
    kernelParams = ["mem_sleep_default=deep"];
    extraModulePackages = [pkgs.linuxPackages.broadcom_sta];
    blacklistedKernelModules = ["b43" "bcma" "brcmsmac" "ssb" "brcmfmac"];
    supportedFilesystems = ["cifs" "ntfs"];
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    initrd = {
      availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
      kernelModules = [];
    };

    # MacBook Pro 2014 spezifische Kernel-Module
    # WiFi is handled by nixos-hardware (brcmfmac via broadcom-43xx); do not use wl here
    kernelModules = [
      "kvm-intel"
      "applesmc" # Apple System Management Controller
      "coretemp" # CPU-Temperatur
      "ftdi_sio"
      "pl2303"
      "ch341"
      "tun"
    ];
  };

  # Firmware handled by nixos-hardware; keep redistributable firmware enabled
  hardware = {
    enableRedistributableFirmware = true;

    cpu.intel.updateMicrocode =
      lib.mkDefault config.hardware.enableRedistributableFirmware;

    # Grafik - Intel HD Graphics 4000/5000 Serie
    graphics = {
      enable = true;
      enable32Bit = true;
      extraPackages = with pkgs; [
        # Defer Intel VAAPI drivers to nixos-hardware (MacBookPro11,4)
        # Keep only translation layers
        vaapiVdpau
        libvdpau-va-gl
      ];
    };
  };

  # Dateisysteme (von nixos-generate-config)
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e4b2dd16-ed3d-4729-8a18-2d88ecc9d9db";
    fsType = "ext4";
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/67E3-17ED";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };
  swapDevices = [];

  # Hardware-Platform (von nixos-generate-config)
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
