# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];

  # MacBook Pro 2014 spezifische Kernel-Module
  boot.kernelModules = [
    "kvm-intel"
    # WiFi: Versuche proprietären Treiber statt brcmfmac
    "wl" # Broadcom proprietärer Treiber
    "applesmc" # Apple System Management Controller
    "coretemp" # CPU-Temperatur
  ];

  # Proprietärer Broadcom-Treiber für bessere WiFi-Kompatibilität
  boot.extraModulePackages = [config.boot.kernelPackages.broadcom_sta];

  # Blacklist konkurrierende Treiber
  boot.blacklistedKernelModules = [
    "brcmfmac"
    "brcmsmac"
    "bcma"
    "ssb"
  ];

  # Firmware für MacBook-Hardware
  hardware.enableRedistributableFirmware = true;
  hardware.firmware = with pkgs; [
    linux-firmware # Enthält Broadcom WiFi-Firmware
    broadcom-bt-firmware # Bluetooth-Firmware
  ];

  nixpkgs.config = {
    allowUnfree = true;
    permittedInsecurePackages = [
      "broadcom-sta"
    ];
  };
  # MacBook-spezifische Kernel-Parameter
  boot.kernelParams = [
    # WiFi-Stabilität
    "pcie_aspm=off"
    # Bessere macOS-Kompatibilität
    "acpi_osi=Darwin"
    # Apple-Tastatur Funktionstasten
    "hid_apple.fnmode=1"
    # Cmd/Alt Tausch auf Hardware-Ebene
    "hid_apple.swap_opt_cmd=1"
  ];

  # Dateisysteme (von nixos-generate-config)
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e4b2dd16-ed3d-4729-8a18-2d88ecc9d9db";
    fsType = "ext4";
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/67E3-17ED";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };
  swapDevices = [];

  # Netzwerk (von nixos-generate-config)
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20u5.useDHCP = lib.mkDefault true;

  # Hardware-Platform (von nixos-generate-config)
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # MacBook Pro 2014 Hardware-Optimierungen

  # Grafik - Intel HD Graphics 4000/5000 Serie
  hardware.opengl = {
    enable = true;
    driSupport32Bit = true;
    extraPackages = with pkgs; [
      intel-media-driver # VA-API für Intel
      vaapiIntel # Hardware-Beschleunigung
      vaapiVdpau
      libvdpau-va-gl
    ];
  };

  # Bluetooth für MacBook Pro 2014 - Erweiterte Konfiguration
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    package = pkgs.bluez;
    settings = {
      General = {
        Enable = "Source,Sink,Media,Socket";
        Experimental = true;
        # MacBook-spezifische Bluetooth-Einstellungen
        ControllerMode = "dual";
        FastConnectable = true;
        ReconnectAttempts = 7;
        ReconnectIntervals = "1, 2, 4, 8, 16, 32, 64";
      };

      Policy = {
        AutoEnable = true;
        ReconnectUUIDs = "00001108-0000-1000-8000-00805f9b34fb,0000111e-0000-1000-8000-00805f9b34fb,0000110a-0000-1000-8000-00805f9b34fb,0000110b-0000-1000-8000-00805f9b34fb";
      };
    };
  };

  # Bluetooth-Services
  services.blueman.enable = true;

  # Zusätzliche Bluetooth-Unterstützung
  environment.systemPackages = with pkgs; [
    bluez-tools
    bluez-alsa # Für Audio über Bluetooth
  ];

  # Energieverwaltung: TLP entfernt wegen Konflikt mit power-profiles-daemon
  # services.tlp = { ... };  # Entfernt - Konflikt mit power-profiles-daemon

  # Alternative Energieverwaltung für MacBook (falls gewünscht)
  # services.power-profiles-daemon.enable = true;  # Wird meist automatisch aktiviert

  # Hintergrundbeleuchtung für MacBook - manuell konfiguriert
  # hardware.brightnessctl.enable = true;  # Entfernt - nicht verfügbar

  # udev-Regeln für MacBook-spezifische Hardware
  services.udev.extraRules = ''
    # MacBook Tastatur-Hintergrundbeleuchtung
    SUBSYSTEM=="leds", KERNEL=="smc::kbd_backlight", ACTION=="add", RUN+="${pkgs.coreutils}/bin/chmod g+w /sys/class/leds/%k/brightness", RUN+="${pkgs.coreutils}/bin/chgrp video /sys/class/leds/%k/brightness"

    # MacBook Bildschirm-Helligkeit
    SUBSYSTEM=="backlight", KERNEL=="intel_backlight", ACTION=="add", RUN+="${pkgs.coreutils}/bin/chmod g+w /sys/class/backlight/%k/brightness", RUN+="${pkgs.coreutils}/bin/chgrp video /sys/class/backlight/%k/brightness"
  '';
}
